/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MenuItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'price' : bigint,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'tableNumber' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'menuItem' : MenuItem, 'quantity' : bigint }
export type OrderStatus = { 'new' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export interface ShopSettings {
  'logo' : [] | [ExternalBlob],
  'shopName' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateAsOwner' : ActorMethod<[string], boolean>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getShopSettings' : ActorMethod<[], ShopSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, bigint, Array<OrderItem>], Order>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItem], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateShopSettings' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];